version: '3'
services:
  web:
    build:
      context: . # This and the following are not necessary if
      dockerfile: Dockerfile.dev # i use default Dockerfile name
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./src:/app/src
